app:
  chaosCenter:
    endpoint: http://chaoscenter.litmus.svc.cluster.local
    projectId: litmus-project-1
    clusterId: cluster-1

agent:
  name: my-agent
  version: "1.0.0"
  vendor: "Litmus"

  mode: active          # Litmus agents are usually active
  scope: cluster        # cluster / namespace

  capabilities:
    - pod-delete
    - pod-cpu-hog

  supportedExperiments:
    - pod-delete
    - pod-cpu-hog

  containerImage:
    registry: docker.io
    repository: nginx
    tag: latest

env:
  mongoUri: mongodb://mongo-mongodb:27017

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"

rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch", "delete"]
