{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.agent.name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.agent.name }}-sa
roleRef:
  kind: Role
  name: {{ .Values.agent.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
